# Generated by Django 4.1.1 on 2022-09-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_software_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slack',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slack'),
        ),
    ]
